version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - php
  php:
    build: ./docker/php
    links:
      - mysql
    volumes:
      - ./:/var/www
#  mysql:
#    image: mysql
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./docker/mysql:/etc/mysql
